### ISSUE TITLE
Project Detail Page (when you click on a specific project). Issue with data that gets rendered. See Comments.

### ISSUE THREAD

**Issue by Dan-Y-Ko** [chingu-voyages/v8-bears-team-01#62]
On page load, it initially shows created by: and description: then gets populated with the data. The quick transition from having empty fields to populated one is not good ux and it needs to render the created by: and description: with the actual data only. Put in either a loader (plenty of loaders used in the project) or another method, when data gets loaded in.

**Comment by EkhatorOwen** [comment]
Yeah, I noticed this. I will look for a way around it.

**Comment by EkhatorOwen** [comment]
This can be be fixed if there's a way to get the loading state with the current Redux setup. Usually with `Redux-promise-middleware` you can get the loading state and assign a loader to that.

**Comment by Dan-Y-Ko** [comment]
The current setup is using Thunk, so similar solution can be used around thunk?

**Comment by EkhatorOwen** [comment]
Fixed in #66. It turns out the problem was simpler than I had imagined. All I needed to do was add a loading state to the local state and then change it when the redux action is fulfilled.
