### ISSUE TITLE
Green underline in the nav should only display when user is on that specific page. It shouldn't appear when user is on homepage. See screenshot below

### ISSUE THREAD

**Issue by Dan-Y-Ko** [chingu-voyages/v8-bears-team-01#63]
Correct: ![](https://i.imgur.com/z6l3vjf.png)

Incorrect: ![](https://i.imgur.com/dqkwP8w.png)

**Comment by AbbyJoe** [comment]
seen

**Comment by EkhatorOwen** [comment]
On the first inspection, this would seem like a CSS issue. However, in trying to fix it, you would discover it's a JS issue because the styles are set programmatically. PR #65 fixes this error.
